"""remove JoinIU

Revision ID: 8e5046d9ec16
Revises: a9de83368f44
Create Date: 2022-05-17 13:48:19.861170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5046d9ec16'
down_revision = 'a9de83368f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('JoinIU')
    op.drop_table('Roles')
    op.add_column('Issues', sa.Column('submitter_id', sa.Integer(), nullable=False))
    op.add_column('Issues', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Issues', 'Users', ['submitter_id'], ['id'])
    op.create_foreign_key(None, 'Issues', 'Users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Issues', type_='foreignkey')
    op.drop_constraint(None, 'Issues', type_='foreignkey')
    op.drop_column('Issues', 'assignee_id')
    op.drop_column('Issues', 'submitter_id')
    op.create_table('JoinIU',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['Issues.id'], name='JoinIU_issue_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], name='JoinIU_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='JoinIU_user_id_fkey'),
    sa.PrimaryKeyConstraint('issue_id', 'user_id', name='JoinIU_pkey')
    )
    op.create_table('Roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Roles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Roles_pkey'),
    sa.UniqueConstraint('role', name='Roles_role_key')
    )
    # ### end Alembic commands ###
