"""add column in IssueType model

Revision ID: c0ddd3699866
Revises: 0835392cad9f
Create Date: 2022-05-10 20:56:57.103491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ddd3699866'
down_revision = '0835392cad9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IssueTypes', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IssueTypes', 'description')
    # ### end Alembic commands ###
