"""Redesign JoinIU

Revision ID: e820507543cf
Revises: 06ac86023da3
Create Date: 2022-05-11 15:12:38.217809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e820507543cf'
down_revision = '06ac86023da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JoinIU',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_submitter', sa.Boolean(), nullable=False),
    sa.Column('is_assignee', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['Issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'user_id')
    )
    op.drop_table('Invites')
    op.drop_constraint('Issues_submitter_id_fkey', 'Issues', type_='foreignkey')
    op.drop_constraint('Issues_assignee_id_fkey', 'Issues', type_='foreignkey')
    op.drop_column('Issues', 'submitter_id')
    op.drop_column('Issues', 'assignee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Issues', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Issues', sa.Column('submitter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Issues_assignee_id_fkey', 'Issues', 'Users', ['assignee_id'], ['id'])
    op.create_foreign_key('Issues_submitter_id_fkey', 'Issues', 'Users', ['submitter_id'], ['id'])
    op.create_table('Invites',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['Issues.id'], name='Invites_issue_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='Invites_user_id_fkey'),
    sa.PrimaryKeyConstraint('issue_id', 'user_id', name='Invites_pkey')
    )
    op.drop_table('JoinIU')
    # ### end Alembic commands ###
