"""implement roles

Revision ID: a9de83368f44
Revises: 11f052d0a5d4
Create Date: 2022-05-12 14:05:29.569283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9de83368f44'
down_revision = '11f052d0a5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.drop_constraint('Issues_assignee_id_fkey', 'Issues', type_='foreignkey')
    op.drop_constraint('Issues_submitter_id_fkey', 'Issues', type_='foreignkey')
    op.drop_column('Issues', 'assignee_id')
    op.drop_column('Issues', 'submitter_id')
    op.add_column('JoinIU', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'JoinIU', 'Roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'JoinIU', type_='foreignkey')
    op.drop_column('JoinIU', 'role_id')
    op.add_column('Issues', sa.Column('submitter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Issues', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Issues_submitter_id_fkey', 'Issues', 'Users', ['submitter_id'], ['id'])
    op.create_foreign_key('Issues_assignee_id_fkey', 'Issues', 'Users', ['assignee_id'], ['id'])
    op.drop_table('Roles')
    # ### end Alembic commands ###
