"""submitter and assignee relationships

Revision ID: d684a56d9242
Revises: e820507543cf
Create Date: 2022-05-12 12:59:26.855882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd684a56d9242'
down_revision = 'e820507543cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Issues', sa.Column('submitter_id', sa.Integer(), nullable=False))
    op.add_column('Issues', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Issues', 'Users', ['assignee_id'], ['id'])
    op.create_foreign_key(None, 'Issues', 'Users', ['submitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Issues', type_='foreignkey')
    op.drop_constraint(None, 'Issues', type_='foreignkey')
    op.drop_column('Issues', 'assignee_id')
    op.drop_column('Issues', 'submitter_id')
    # ### end Alembic commands ###
